---
- hosts: Cisco_All
  gather_facts: no
  connection: local
  tasks:
    - name: Config Backup
      ios_command:
        commands:
          - show run
        authorize: true
        auth_pass: **********
        timeout: 30
      register: result
    - name: save config to file
      copy:
        content: "{{ result.stdout[0]}}"
        dest: "/var/lib/awx/projects/GitLab/cisco-get-config/{{ inventory_hostname }}.txt"
